### ISSUE TITLE
Allow use with jellyfin

### ISSUE THREAD

**Issue by kubo6472** [I-am-PUID-0/pd_zurg#2]
**Is your feature request related to a problem? Please describe.**
Currently limited usage to plex

**Describe the solution you'd like**

Allow to either set PLEX_USER/PLEX_TOKEN... or a JELLYFIN_APIKEY and JELLYFIN_ADDRESS

**Comment by kubo6472** [comment]
I put this in zurg, works fine:
```
on_library_update: |
  for arg in "$@"
  do
      curl -v -X POST -H "X-MediaBrowser-Token: censored" https://domain.tld/library/refresh
  done
```

**Comment by I-am-PUID-0** [comment]
Feature added in Version [2.0.0]

**Comment by kubo6472** [comment]
![image](https://github.com/I-am-PUID-0/pd_zurg/assets/26146502/0ea7d070-b69d-444e-86ec-7ac909ae0802)
this is what breaks it, it tries connecting to plex, because your way of manipulating the config file adds this empty bracket, which is what triggers plex_debrid to start connecting to plex.

**Comment by kubo6472** [comment]
Possibly fixable by editing this: 
![image](https://github.com/I-am-PUID-0/pd_zurg/assets/26146502/08f976f7-14c1-4130-99da-cfb1e4fd0217)

**Comment by kubo6472** [comment]
```
Exception in thread Thread-1 (threaded):
pd_zurg  | Traceback (most recent call last):
pd_zurg  |   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
pd_zurg  |     self.run()
pd_zurg  |   File "/usr/lib/python3.11/threading.py", line 982, in run
pd_zurg  |     self._target(*self._args, **self._kwargs)
pd_zurg  |   File "/plex_debrid/ui/__init__.py", line 408, in threaded
pd_zurg  |     library = content.classes.library()[0]()
pd_zurg  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pd_zurg  |   File "/plex_debrid/content/services/trakt.py", line 616, in __new__
pd_zurg  |     ui_print('[trakt] getting ' + current_user[0] + "'s" + ' entire trakt collection ...')
pd_zurg  |                                   ~~~~~~~~~~~~^^^
pd_zurg  | IndexError: list index out of range
```

**Comment by I-am-PUID-0** [comment]
> Possibly fixable by editing this: ![image](https://private-user-images.githubusercontent.com/26146502/298307062-08f976f7-14c1-4130-99da-cfb1e4fd0217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODE4MTYsIm5iZiI6MTcwNTk4MTUxNiwicGF0aCI6Ii8yNjE0NjUwMi8yOTgzMDcwNjItMDhmOTc2ZjctMTRjMS00MTMwLTk5ZGEtY2ZiMWU0ZmQwMjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAzNDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOGY1MjczYjYxMGYxOTZmMzMwOWNhOWU5NWQyZDk0Y2NkZmE2MzRmOGU4MjQ1MDkzYmVkZDA0YmNmNTRlODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HOzcj3VHp1zG1ai6556DyTn_8c8zv0sJtLvtb6jIlCg)

Fixed in Version [2.0.3]

**Comment by I-am-PUID-0** [comment]
> ```
> Exception in thread Thread-1 (threaded):
> pd_zurg  | Traceback (most recent call last):
> pd_zurg  |   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
> pd_zurg  |     self.run()
> pd_zurg  |   File "/usr/lib/python3.11/threading.py", line 982, in run
> pd_zurg  |     self._target(*self._args, **self._kwargs)
> pd_zurg  |   File "/plex_debrid/ui/__init__.py", line 408, in threaded
> pd_zurg  |     library = content.classes.library()[0]()
> pd_zurg  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> pd_zurg  |   File "/plex_debrid/content/services/trakt.py", line 616, in __new__
> pd_zurg  |     ui_print('[trakt] getting ' + current_user[0] + "'s" + ' entire trakt collection ...')
> pd_zurg  |                                   ~~~~~~~~~~~~^^^
> pd_zurg  | IndexError: list index out of range
> ```

I have finally figured this one out! The "Trakt refresh user" needs to be set in the plex_debrid settings.json; unfortunately, the only way to do so is by authorizing and adding your Trakt user by editing the Library collection service with the plex_debrid UI!

**Comment by WagnerJon** [comment]
Still getting the error above, even when a trakt user is set + authorized via the UI.

**Comment by WagnerJon** [comment]
Still getting the error above. Even with added and authorized trakt user via the plex_debrid UI
